# Generated by Django 4.2.3 on 2023-07-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixboitereexpedition',
            name='mois_abonnement',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reexpedition',
            name='mois_abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reexpedition_mois_abonnement', to='playground.prixboitereexpedition'),
        ),
    ]
