# Generated by Django 4.2.3 on 2023-07-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prixboitereexpedition',
            name='mois_abonnement',
        ),
    ]
