# Generated by Django 4.2.3 on 2023-07-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_prixboitereexpedition_mois_abonnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reexpedition',
            name='matricule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.agent'),
        ),
        migrations.AlterField(
            model_name='reexpedition',
            name='mois_abonnement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reexpedition_mois_abonnement', to='playground.prixboitereexpedition'),
        ),
        migrations.AlterField(
            model_name='reexpedition',
            name='num_panier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.panier'),
        ),
        migrations.AlterField(
            model_name='reexpedition',
            name='type_expediteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reexpedition_type_expediteur', to='playground.prixboitereexpedition'),
        ),
    ]
