# Generated by Django 4.2.3 on 2023-07-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_prixboitereexpedition_mois_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prixboitereexpedition',
            name='mois_abonnement',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
