# Generated by Django 4.2.3 on 2023-07-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_reexpedition_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='compteur',
            field=models.IntegerField(null=True),
        ),
    ]
